config/routes.rb
Gratefulness::Application.routes.draw do

  root to: 'home#index'

  resources :users do
    get 'entries/random', :to => 'entries#random'
    get 'entries/recent', :to => 'entries#recent'
    resources :entries
  end

  match 'signup' => 'users#new', :as => :signup

  resources :user_sessions

  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login

  match 'home' => 'home#index'

  match 'about' => 'about#index', :as => :about
  match 'what' => 'about#what', :as => :what

end

app/models/gratefulness_entry.rb
class GratefulnessEntry < ActiveRecord::Base

  attr_accessible :body_text
  attr_accessible :creation_date

  belongs_to :author, class_name: 'User'

  validates :body_text, presence: true
  validates :creation_date, presence: true
  validates :author, presence: true

  def self.previous_entry(author, date_ref)
    return nil if author.nil? || date_ref.nil?
    where('author_id = ? AND creation_date < ?', author.id, date_ref)
    .order('creation_date DESC')
    .limit(1).first
  end

  def self.next_entry(author, date_ref)
    return nil if author.nil? || date_ref.nil?
    where('author_id = ? AND creation_date > ?', author.id, date_ref)
    .order('creation_date ASC')
    .limit(1).first
  end

  def previous
    GratefulnessEntry.previous_entry(self.author, self.creation_date)
  end

  def next
    GratefulnessEntry.next_entry(self.author, self.creation_date)
  end

end

app/models/tl.rb
class Tl

  @@logger = ActiveSupport::TaggedLogging.new(Logger.new("#{Rails.root}/log/development_trace.log"))

  def log(message)
    @@logger.tagged(Time.now.strftime("%Y-%m-%d %H:%M:%S")) { @@logger.info(message) }
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_authentic

  attr_accessible :login
  attr_accessible :email
  attr_accessible :password
  attr_accessible :password_confirmation

  has_many :entries, class_name: 'GratefulnessEntry', foreign_key: 'author_id'

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  # configuration here, see documentation for sub modules of Authlogic::Session
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index
  end

  def what
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery

  layout 'one-column'

  helper_method :current_user_session, :current_user

  private

    def current_user_session
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
    end

    def current_user
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.user
    end

    def require_user
      unless current_user
        store_location
        flash[:notice] = I18n.t('application.must-be-logged-in')
        redirect_to new_user_session_path
        return false
      end
    end

    def require_no_user
      if current_user
        store_location
        flash[:notice] = I18n.t('application.must-be-logged-out')
        redirect_to home_path
        return false
      end
    end

    def store_location
      session[:return_to] = request.url
    end

    def redirect_back_or_default(default)
      redirect_to(session[:return_to] || default)
      session[:return_to] = nil
    end

    def not_found
      status_code_response(404, :not_found)
    end

    def no_access
      status_code_response(403, :forbidden)
    end

    def unprocessable
      status_code_response(422, :unprocessable_entity)
    end

    def status_code_response(code, status)
      render file: File.join(Rails.root, "public/#{code}"),
             formats: [:html],
             status: status,
             layout: false
    end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  before_filter :require_user
  before_filter :verify_user_path

	def new
    @entry = GratefulnessEntry.new
	end

  def create
    @entry = GratefulnessEntry.new(params[:gratefulness_entry])
    @entry.creation_date = DateTime.now
    @entry.author = current_user
    if @entry.save
      redirect_to user_entry_path(current_user, @entry)
    else
      unprocessable
    end
  end

  def show
    get_entry!
    not_found and return if @entry.nil?
    no_access if !entry_owned?
  end

  def random
    get_random_entry!
    not_found and return if @entry.nil?
    no_access and return if !entry_owned?
    redirect_to user_entry_path(current_user, @entry)
  end

  def recent
    get_last_entry!
    not_found and return if @entry.nil?
    no_access and return if !entry_owned?
    redirect_to user_entry_path(current_user, @entry)
  end

  def index
    redirect_to new_user_entry_path(current_user)
  end

  private

    def verify_user_path
      no_access if User.find_by_id(params[:user_id]) != current_user
    end

    def get_entry!
      @entry = GratefulnessEntry.find_by_id(params[:id])
    end

    def get_last_entry!
      @entry = GratefulnessEntry.previous_entry(current_user, DateTime.now)
    end

    def get_random_entry!
      offset = rand(current_user.entries.count)
      @entry = current_user.entries.first(offset: offset)
    end

    def entry_owned?
      @entry.try(:author) == current_user
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  before_filter :require_no_user, only: [:new, :create]
  before_filter :require_user, only: :destroy

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = I18n.t('application.login-successful')
      redirect_back_or_default home_path
    else
      render :action => :new
    end
  end

  def destroy
    current_user_session.destroy
    flash[:notice] = I18n.t('application.logout-successful')
    redirect_back_or_default home_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :require_no_user, only: [:new, :create]

  def new
    @user ||= User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = I18n.t('application.account-registered')
      redirect_back_or_default home_path
    else
      render :action => :new
    end
  end

  def show
    not_found
  end

  def edit
    not_found
  end

  def update
    not_found
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/date_time_helper.rb
module DateTimeHelper

  def entry_title_format(dt)
    dt.to_date.strftime('%b %e, %Y')
  end

end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/index.html.haml
%h3
  = t('about.title')

%p
  = t('about.credits')

%p
  %a{ :href => 'https://github.com/millerpeterson/thx-journal', :target => '_blank', :class => 'info-link' }
    = t('about.code')

= link_to t('about.back-home'), home_path, :class => 'pure-button pure-button-primary'

app/views/about/what.html.haml
%h3
  = t('what.title')

%p
  = t('what.p1')

%p
  = t('what.p2')

%p
  = t('what.p3')

%p
  %a{ :href => 'http://greatergood.berkeley.edu/article/item/tips_for_keeping_a_gratitude_journal', :target => '_blank', :class => 'info-link' }
    = t('what.tips')

= link_to t('what.back-home'), home_path, :class => 'pure-button pure-button-primary'

app/views/entries/new.html.haml
%h3
  = entry_title_format(DateTime.now)

%div.entry
  = form_for @entry, :url => user_entries_path(current_user, @entry) do |e|
    = e.text_area :body_text, :rows => "10"
    %br
    %button{ :type => 'submit', :class => 'submit pure-button pure-button-primary' }
      = t('new-entry.submit-form')

app/views/entries/show.html.haml
%div.entry

  %h3
    = entry_title_format(@entry.creation_date)

  %div.entry-body
    = simple_format(@entry.body_text)

  %div.entry-nav
    - if @entry.previous.present?
      = link_to t('entry-nav.previous'), user_entry_path(current_user, @entry.previous), :class => 'pure-button pure-button-primary'
    - if current_user.entries.size > 1
      = link_to t('entry-nav.random'), user_entries_random_path(current_user), :class => 'pure-button pure-button-primary'
    - if @entry.next.present?
      = link_to t('entry-nav.next'), user_entry_path(current_user, @entry.next), :class => 'pure-button pure-button-primary'

app/views/home/index.html.haml
%h1
  = t('home.main-title')
%h2
  = t('home.sub-title')

%div.button_container
- if current_user

  = link_to t('home.new'), new_user_entry_path(current_user), :class => 'pure-button pure-button-primary'
  - if current_user.entries.any?
    = link_to t('home.recent'), user_entries_recent_path(current_user), :class => 'pure-button pure-button-primary'
  - if current_user.entries.size > 1
    = link_to t('home.random'), user_entries_random_path(current_user), :class => 'pure-button pure-button-primary'

- else

  = link_to t('home.what'), what_path, :class => 'pure-button pure-button-primary'
  = link_to t('home.login'), login_path, :class => 'pure-button pure-button-primary'
  = link_to t('home.sign-up'), signup_path, :class => 'pure-button pure-button-primary'

app/views/layouts/_topmenu.html.haml
%div#top-menu{ :class => 'pure-menu pure-menu-open pure-menu-horizontal' }

  %ul#top-menu-items
    %li
      = link_to t('top-menu.site-title'), home_path
    - if current_user
      %li
        = link_to t('top-menu.logout'), logout_path
    %li
      = link_to t('top-menu.about'), about_path

</div>

app/views/layouts/application.html.haml
!!!

%html

  %head

    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

    = javascript_include_tag "http://yui.yahooapis.com/3.12.0/build/yui/yui-min.js"

    %title
      = @page_title or t('application.base-title')

  %body
    = yield :body

app/views/layouts/one-column.html.haml
- content_for :body do

  %div{ class: 'menu-content' }
    = render partial: 'layouts/topmenu'

  %div{ class: 'main-content' }
    = yield

= render template: 'layouts/application'

app/views/session/new.html.haml
= form_tag authenticate_path, :class => 'pure-form pure-form-stacked' do

  %legend
    = t('login.form-title')

  - if flash[:invalid_login]
    %div{ :class => 'error_messages'}
      %ul
        %li
          = flash[:invalid_login]

  = label_tag :email, t('login.field-email')
  = text_field_tag :email, params[:email]

  = label_tag :password, t('login.field-password')
  = password_field_tag :password

  %button{ :type => 'submit', :class => 'submit pure-button pure-button-primary' }
    = t('login.submit-form')

app/views/user_sessions/new.html.haml
- form_style = { :class => 'pure-form pure-form-stacked' }
= form_for @user_session, :url => user_sessions_path, :html => form_style do |f|
  %fieldset
    %legend
      = t('login.form-title')

    - if @user_session.errors.any?
      %div{ :class => 'error_messages' }
        %ul
          - for message in @user_session.errors.full_messages
            %li
              = message

    = f.label :login, t('login.field-login')
    = f.text_field :login

    = f.label :password, t('login.field-password')
    = f.password_field :password

    %button{ :type => 'submit', :class => 'submit pure-button pure-button-primary' }
      = t('login.submit-form')

app/views/users/new.html.haml
= form_for @user, :html => { :class => 'pure-form pure-form-stacked' } do |f|
  %fieldset
    %legend
      = t('sign-up.form-title')

    - if @user.errors.any?
      %div{ :class => 'error_messages' }
        %ul
          - for message in @user.errors.full_messages
            %li
              = message

    = f.label :login, 'Nickname'
    = f.text_field :login

    = f.label :email, t('sign-up.field-email')
    = f.text_field :email

    = f.label :password, t('sign-up.field-password')
    = f.password_field :password

    = f.label :password_confirmation, t('sign-up.field-password-confirmation')
    = f.password_field :password_confirmation

    %button{ :type => 'submit', :class => 'submit pure-button pure-button-primary' }
      = t('sign-up.submit-form')